// Generated by https://quicktype.io
import Gender from './gender.enum';
import Species from './species.enum';
import Status from './status.enum';

export interface ICharacter {
  id:       number;
  name:     string;
  status:   Status;
  species:  Species;
  type:     string;
  gender:   Gender;
  origin:   Location;
  location: Location;
  image:    string;
  episode:  string[];
  url:      string;
  created:  string;
}


export interface Location {
  name: string;
  url:  string;
}