// Generated by https://quicktype.io
import type { ICharacter } from './character.interface';

export interface ICharacters {
  info:    Info;
  results: ICharacter[];
}

export interface Info {
  count: number;
  pages: number;
  next:  string;
  prev:  null;
}
